# Generated by Django 4.0.4 on 2022-05-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_candidate_course_candidate_job_alter_candidate_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
