# Generated by Django 4.0.4 on 2022-05-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_candidate_phone_alter_employer_phone'),
        ('accounts', '0005_course_views_job_views'),
    ]

    operations = [
    ]
