name: Deploy to Heroku

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create a random secret
        run: |
          echo "SECRET_KEY=$(openssl rand -hex 32)" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
        env:
          HD_SECRET_KEY: ${{ env.SECRET_KEY }}
          HD_DATABASE_URL: ${{ secrets.DATABASE_URL }}
